### ISSUE TITLE
selection bar on command pallete selection not visible since last (few?) vscode update

### ISSUE THREAD

**Issue by verma16Ayush** [huytd/vscode-tokyo-city#3]
Hi, so I have been having this issue with this theme lately, the selected option on the command palette list does not show a selection bar. see the below screenshots for more detail,
![Screenshot from 2021-06-16 21-03-51](https://user-images.githubusercontent.com/56771900/122249348-63607d80-cee6-11eb-8c39-262665f1dab0.png)
There is no way to know which option is selected except for the settings icon next to the option. the desired result should be like this
![Screenshot from 2021-06-16 21-05-36](https://user-images.githubusercontent.com/56771900/122249605-9d318400-cee6-11eb-8f5c-c43223584ac2.png)
This has been my constant theme for the last few years. I really would love if it could get fixed. The issue persists with the light mode version of the TokyoCity theme as well

**Comment by huytd** [comment]
Hey, thank you so much, yes I've noticed this issue as well. Fix will come up in the next few days.

**Comment by huytd** [comment]
Version 0.2.3 has been published to fix this issue. Please upgrade it from the marketplace. Thanks.
