### ISSUE TITLE
Colour of cursor/selection with regular and dark version

### ISSUE THREAD

**Issue by jcnils** [huytd/vscode-tokyo-city#6]
Hi, Thank you for this great theme.

I am having some problems with the colour of cursor/selection, mostly on terminal.

Terminal is out of focus:
![image](https://user-images.githubusercontent.com/961151/164532002-7c83c51f-1611-4618-83f1-e0ba791e98ce.png)

Terminal on focus:
![image](https://user-images.githubusercontent.com/961151/164532043-c3d97a17-4de7-44f5-b8a9-e7e2d0d44ea0.png)

Terminal selection
![image](https://user-images.githubusercontent.com/961151/164532118-a801424d-371f-493c-b192-6be57b273535.png)

Text editor selection (it works well when the colour of the text has more contrast or with the Dark theme) 
![image](https://user-images.githubusercontent.com/961151/164532197-3e2fa4eb-974f-439f-aacd-aeb25ee01115.png)
![image](https://user-images.githubusercontent.com/961151/164532703-e14fd6a1-2992-4ef4-9093-09089822ab63.png)

The light colour is ok.
![image](https://user-images.githubusercontent.com/961151/164533782-574a19a5-14b5-4222-ae50-5bcb5038fc44.png)

I saw that the terminal background is the same as the foreground, and it is causing the problem with the cursor.
![image](https://user-images.githubusercontent.com/961151/164535476-4e3fe5f4-b1e2-4b82-a30f-ef0c94dffafb.png)

For the selection I understand that the theme is supposed to be low contrast.

I don't know if the terminal background and foreground was intentional. If not I can send a PR if you want it.

Cheers.

**Comment by huytd** [comment]
Hey, thanks for spotting this, it's not intentional. And sorry, I was probably using an override terminal theme at the time I composed this theme and might have missed it. My bad.

It would be great if you can submit a PR for it!

**Comment by jcnils** [comment]
Haha, no worries, it happens. and I am glad I can help.

https://github.com/huytd/vscode-tokyo-city/pull/7

While debugging I found another difference on the main theme. I also added a fix for that, I hope it is ok.

**Comment by huytd** [comment]
Thank you so much!!!!
